QuantumIT/Controllers/ElmahController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuantumIT.Models;

namespace QuantumIT.Controllers
{
    public class ElmahController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Elmah
        public ActionResult Index()
        {
            return View(db.ElmahErrors.ToList());
        }

        // GET: Elmah/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ElmahError elmahError = db.ElmahErrors.Find(id);
            if (elmahError == null)
            {
                return HttpNotFound();
            }
            return View(elmahError);
        }

        // GET: Elmah/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Elmah/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ErrorId,Application,Host,Type,Source,Message,User,StatusCode,TimeUtc,Sequence,AllXml")] ElmahError elmahError)
        {
            if (ModelState.IsValid)
            {
                elmahError.ErrorId = Guid.NewGuid();
                db.ElmahErrors.Add(elmahError);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(elmahError);
        }

        // GET: Elmah/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ElmahError elmahError = db.ElmahErrors.Find(id);
            if (elmahError == null)
            {
                return HttpNotFound();
            }
            return View(elmahError);
        }

        // POST: Elmah/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ErrorId,Application,Host,Type,Source,Message,User,StatusCode,TimeUtc,Sequence,AllXml")] ElmahError elmahError)
        {
            if (ModelState.IsValid)
            {
                db.Entry(elmahError).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(elmahError);
        }

        // GET: Elmah/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ElmahError elmahError = db.ElmahErrors.Find(id);
            if (elmahError == null)
            {
                return HttpNotFound();
            }
            return View(elmahError);
        }

        // POST: Elmah/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ElmahError elmahError = db.ElmahErrors.Find(id);
            db.ElmahErrors.Remove(elmahError);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuantumIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Restfull API", "RestfullAPI")</li>
                    <li>@Html.ActionLink("Log View", "Index", "Elmah")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - QuantumIT Test</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>